import test from 'node:test';
import assert from 'node:assert/strict';
import {requirement,dashboardRows,chapterStories} from '../src/story/storyState.js';
import {readFileSync} from 'node:fs';
test('every chapter carries problem, action and outcome for the same requirement',()=>{assert.equal(chapterStories.length,7);for(const chapter of chapterStories){assert.ok(chapter.problem.length>20);assert.ok(chapter.action.length>20);assert.ok(chapter.outcome.length>20)}assert.match(requirement.request,/filtered.*CSV/);});
test('browser scenario has a concrete filter comparison',()=>{const ready=dashboardRows.filter(r=>r.status==='Ready');assert.equal(ready.length,2);assert.equal(dashboardRows.length,3);assert.notEqual(ready.length,dashboardRows.length);assert.equal(ready[0].project,'Website');});
test('conversation links open the internal PR pane rather than an invented external PR',()=>{const source=readFileSync(new URL('../src/story/StoryShell.jsx',import.meta.url),'utf8');assert.match(readFileSync(new URL('../src/story/ExternalChat.jsx',import.meta.url),'utf8'),/chat-pr-link/);assert.match(source,/setRight\('Pull request'\)/);assert.ok(!/https:\/\/github\.com\/[^'"\s]+\/pull\/42/.test(source));});
test('current task states and human review boundary appear in the workspace',()=>{const source=readFileSync(new URL('../src/story/MusterWorkbench.jsx',import.meta.url),'utf8')+readFileSync(new URL('../src/story/StoryShell.jsx',import.meta.url),'utf8');for(const word of ['To do','In Progress','In Review','Blocked','Done','Request changes','Approve'])assert.ok(source.includes(word));});
test('no prototype mutation is wired to a messaging, provider or git API',()=>{for(const name of ['StoryShell.jsx','MusterWorkbench.jsx','ExternalChat.jsx','DashboardCheck.jsx','App.jsx']){const source=readFileSync(new URL('../src/story/'+name,import.meta.url),'utf8');assert.ok(!/fetch\s*\(|XMLHttpRequest|WebSocket\s*\(/.test(source));}});

test('external chat has workspace/channel rails, named humans and a threaded app reply',()=>{const source=readFileSync(new URL('../src/story/ExternalChat.jsx',import.meta.url),'utf8');for(const text of ['slack-workspace-rail','slack-channel-sidebar','Northstar Labs','Alex Morgan','Jamie Lee','slack-message-author','<time','@Muster','slack-thread','APP','Pull request #42'])assert.ok(source.includes(text));});
test('external Slack and Muster workspace are visibly separate surfaces',()=>{const shell=readFileSync(new URL('../src/story/StoryShell.jsx',import.meta.url),'utf8'),native=readFileSync(new URL('../src/story/MusterWorkbench.jsx',import.meta.url),'utf8');assert.ok(shell.includes('external-chat-titlebar'));assert.ok(shell.includes('faithful-muster-shell'));assert.ok(native.includes('chat-workspace-transition'));assert.ok(native.includes('Reply back in {channel}'));});

test('external chat renders the request, human mention and returned PR in the same thread',async()=>{
  const {build}=await import('esbuild');
  const {createRequire}=await import('node:module');
  const result=await build({stdin:{contents:"import React from 'react'; import {renderToStaticMarkup} from 'react-dom/server'; import ExternalChat from './ExternalChat.jsx'; export function render(step){return renderToStaticMarkup(<ExternalChat channel='Slack' step={step} final={step>=11} onTag={()=>{}} onRoute={()=>{}} onPR={()=>{}}/>)}",resolveDir:new URL('../src/story/',import.meta.url).pathname,loader:'jsx'},bundle:true,write:false,platform:'node',format:'cjs',external:['react','react-dom/server']});
  const module={exports:{}};new Function('require','module','exports',result.outputFiles[0].text)(createRequire(import.meta.url),module,module.exports);
  const incoming=module.exports.render(0),tagged=module.exports.render(2),returned=module.exports.render(12);
  for(const html of [incoming,tagged,returned]){assert.match(html,/Slack workspace conversation/);assert.match(html,/Northstar Labs/);assert.match(html,/Alex Morgan/);assert.match(html,/slack-thread/);}
  assert.match(tagged,/@Muster/);assert.match(tagged,/Jamie Lee/);assert.match(tagged,/9:42 AM/);assert.match(tagged,/Open in Muster/);assert.match(returned,/Pull request #42/);assert.match(returned,/9:58 AM/);assert.match(returned,/slack-bot-reply/);
});

test('native app anatomy preserves screenshot-backed sidebar and task review',()=>{const source=readFileSync(new URL('../src/story/MusterWorkbench.jsx',import.meta.url),'utf8');for(const text of ['muster-breadcrumb','Inbox','New chat','Search chats','Memory','Automations','Ledger','Folders','Projects','Settings','Skills & plugins','Accounts & providers','muster-roster-canvas','muster-profile-relationships','muster-task-conversation','Handoff','Receipt','Review 1 of 1','Note (required to request changes','1 earlier decision','Blocking','Start {profile.name} in a worktree','Read-only layers','Not staged'])assert.ok(source.includes(text),text);});
test('product clip sits within the agent chapter, not as a separate footer video',()=>{const source=readFileSync(new URL('../src/story/App.jsx',import.meta.url),'utf8');assert.ok(source.includes("j===2&&<div className='chapter-product-clip'"));assert.ok(!source.includes("className='tour-wrap'"));});

test('native page components render roster, profile, task and resource anatomy',async()=>{
 const {build}=await import('esbuild');const {createRequire}=await import('node:module');
 const result=await build({stdin:{contents:`import React from 'react';import {renderToStaticMarkup} from 'react-dom/server';import MusterWorkbench from './MusterWorkbench.jsx';const noop=()=>{};export function render(tab,right=''){return renderToStaticMarkup(<MusterWorkbench tab={tab} right={right} step={6} playing={false} chapter={3} channel='Slack' selected='cto' stateFor={()=>'In Review'} prTab='Conversation' fixed={true} approved={false} requested={false} note='Keep the dashboard filters.' recall={true} receipt={true} browserValid={false} setTab={noop} setStep={noop} setSelected={noop} setRight={noop} setPrTab={noop} setFixed={noop} setApproved={noop} setRequested={noop} setNote={noop} setRecall={noop} setReceipt={noop} setBrowserValid={noop} setPlaying={noop} onChat={noop}/>);}`,resolveDir:new URL('../src/story/',import.meta.url).pathname,loader:'jsx'},bundle:true,write:false,platform:'node',format:'cjs',external:['react','react-dom/server']});
 const module={exports:{}};new Function('require','module','exports',result.outputFiles[0].text)(createRequire(import.meta.url),module,module.exports);
 const roster=module.exports.render('roster'),profile=module.exports.render('agent'),task=module.exports.render('task','Properties'),git=module.exports.render('code','Pull request'),computer=module.exports.render('computer','Computer');
 for(const html of [roster,profile,task,git,computer]){assert.match(html,/Muster Agent workspace/);assert.match(html,/muster-nav/);assert.match(html,/Back to app/);}
 assert.match(roster,/muster-roster-canvas/);assert.match(roster,/Roster/);assert.match(profile,/Reports to/);assert.match(profile,/Pulse/);assert.match(task,/Review 1 of 1/);assert.match(task,/Handoff/);assert.match(task,/Properties/);assert.match(git,/Not staged/);assert.match(git,/Pull request #42/);assert.match(computer,/Scratch sandbox/);assert.match(computer,/Read-only layers/);
});
