import React from 'react';
import {ChatCircleDots,GitBranch,ArrowRight,Hash,Plus,House,EnvelopeSimple} from '@phosphor-icons/react';
import {requirement} from './storyState.js';
function HumanAvatar({person}){return <span className={'slack-human-avatar avatar-'+person} aria-hidden='true'><svg viewBox='0 0 40 40'><circle cx='20' cy='16' r='7'/><path d='M7 40v-8c0-8 26-8 26 0v8Z'/><path className='avatar-hair' d={person==='alex'?'M12 17V12c0-9 17-9 16 2l-3-2-3 1-4-3-5 6Z':'M12 16V11c3-6 14-6 16 1v5l-3-5-12 2Z'}/></svg></span>}
function BotAvatar(){return <span className='slack-bot-avatar'><img src='/favicon.svg' alt=''/></span>}
export default function ExternalChat({channel,step,final,onTag,onRoute,onPR}){const slack=channel==='Slack';return <div className={'external-chat-app '+(slack?'external-slack':'external-telegram')} aria-label={slack?'Slack workspace conversation':'Telegram group conversation'}>
<div className='slack-workspace-rail' aria-label='Workspace rail'><span className='workspace-initial'>N</span><span className='slack-rail-item'><House/><small>Home</small></span><span className='slack-rail-item'><EnvelopeSimple/><small>DMs</small></span><span className='slack-rail-item'><ChatCircleDots/><small>Activity</small></span><span className='slack-rail-add'><Plus/></span></div>
<aside className='slack-channel-sidebar'><div className='slack-workspace-name'><b>Northstar Labs</b><span>⌄</span></div><div className='slack-sidebar-shortcuts'><span>Threads</span><span>Drafts & sent</span></div><small>Channels</small><div className='slack-channel muted'><Hash/>general</div><div className='slack-channel selected' aria-current='page'><Hash/>product-development</div><div className='slack-channel muted'><Hash/>engineering</div><small>Direct messages</small><div className='slack-dm'><i/>Alex Morgan</div><div className='slack-dm'><i/>Jamie Lee <span>(you)</span></div><div className='slack-app-section'><small>Apps</small><div><BotAvatar/>Muster</div></div></aside>
<section className='slack-conversation'><header className='slack-channel-header'><div><h3>{slack?'# product-development':'Product development'}</h3><p>{slack?'Alex, Jamie and the product team':'Northstar Labs · group chat'}</p></div><span className='slack-channel-members' aria-label='Three conversation participants'><HumanAvatar person='alex'/><HumanAvatar person='jamie'/><span>3</span></span></header><div className='slack-message-scroll'><div className='slack-day-divider'><span>Today</span></div><article className='slack-message'><HumanAvatar person='alex'/><div><div className='slack-message-author'><b>Alex Morgan</b><time dateTime='09:41'>9:41 AM</time></div><p>{requirement.request}</p><p className='slack-message-context'>It would save us copying the filtered view into a spreadsheet.</p><span className='slack-reaction'>👀 <span>1</span></span></div></article>
<div className='slack-thread' aria-label='Thread on Alex’s CSV export request'><div className='slack-thread-heading'><b>Thread</b><span># product-development</span></div><div className='slack-thread-origin'>Replying to <b>Alex Morgan</b> · CSV export</div>{step>=1?<article className='slack-message slack-human-tag'><HumanAvatar person='jamie'/><div><div className='slack-message-author'><b>Jamie Lee</b><span className='slack-you'>you</span><time dateTime='09:42'>9:42 AM</time></div><p><strong className='slack-mention'>@Muster</strong> take this on. Keep the filters, add tests and show the result before review.</p></div></article>:<button className='tag-muster-button slack-tag-action' onClick={onTag}><ChatCircleDots/>Tag @Muster in this thread</button>}
{step>=2&&<article className='slack-message slack-bot-reply'><BotAvatar/><div><div className='slack-message-author'><b>Muster</b><span className='slack-app-badge'>APP</span><time dateTime={final?'09:58':'09:42'}>{final?'9:58 AM':'9:42 AM'}</time></div><p>{final?'CSV export is ready for review. Active filters are preserved, column headings are included, and the test and browser checks are attached.':'I’ll hand this to the Dashboard project lead. You can inspect the tasks, owners and outputs in Muster.'}</p>{final?<button className='chat-pr-link slack-link-unfurl' onClick={onPR}><GitBranch/><span><b>Add CSV export to the dashboard</b><small>Pull request #42 · feat/csv-export</small><em>Open the change and its checks in Muster <ArrowRight/></em></span></button>:<button className='thread-assignment slack-muster-route' onClick={onRoute}><img src='/favicon.svg' alt=''/><span><b>Open in Muster</b><small>Dashboard → CEO → assigned work</small></span><ArrowRight/></button>}</div></article>}
</div><div className='slack-composer' aria-label='Conversation composer illustration'><span>Reply in thread…</span><div><b>Aa</b><span>＋</span><span>@</span><span>☺</span><i>↵</i></div></div><p className='slack-thread-foot'>Replies stay in the original conversation</p></div></section></div>}
