import React,{useEffect,useState} from 'react';
import {Play,Pause,ArrowCounterClockwise} from '@phosphor-icons/react';
import ExternalChat from './ExternalChat.jsx';
import MusterWorkbench from './MusterWorkbench.jsx';
const bases={1:0,2:2,3:4,4:6,5:8,6:11},ends={1:2,2:4,3:6,4:8,5:11,6:12};
export default function StoryShell({chapter=1,motion=true,enabled=true}){
const[replayCount,setReplayCount]=useState(0),[expanded,setExpanded]=useState(false),[step,setStep]=useState(0),[playing,setPlaying]=useState(false),[tab,setTab]=useState('chat'),[selected,setSelected]=useState('cto'),[right,setRight]=useState(''),[prTab,setPrTab]=useState('Conversation'),[fixed,setFixed]=useState(false),[approved,setApproved]=useState(false),[requested,setRequested]=useState(false),[channel,setChannel]=useState('Slack'),[note,setNote]=useState('Export only the filtered dashboard rows.'),[recall,setRecall]=useState(true),[receipt,setReceipt]=useState(false),[browserValid,setBrowserValid]=useState(false);
useEffect(()=>{if(!enabled){setPlaying(false);return}const n=chapter||1;setStep(bases[n]??0);setTab(n===1?'chat':n===2?'roster':n===3?'agent':n===4?'code':n===5?'computer':'chat');setRight(n===4?'Pull request':n===5?'Computer':'');setPlaying(motion);setRequested(false)},[chapter,enabled]);
useEffect(()=>{if(!motion)setPlaying(false)},[motion]);
useEffect(()=>{if(!playing)return;const max=ends[chapter]??2;const t=setInterval(()=>setStep(v=>{if(chapter===5)return Math.max(v,9);if(v>=max){setPlaying(false);return max}return v+1}),1600);return()=>clearInterval(t)},[playing,chapter]);
const final=step>=11;const stateFor=id=>approved?'Done':requested?'To do':step<2?'To do':step===7&&!fixed&&id==='qa'?'Blocked':step>=9?'In Review':id==='ceo'&&step>=4?'In Review':'In Progress';
function replay(){setReplayCount(v=>v+1);setBrowserValid(false);setStep(bases[chapter]??0);setPlaying(motion);setFixed(false);setApproved(false);setRequested(false);setReceipt(false)};
function backToChat(){setTab('chat');setRight('');if(step>=10){setStep(12);setPlaying(false)}};
return <div className={'story-shell tab-'+tab+(expanded?' shell-expanded':'')+(tab==='chat'?' external-chat-shell':' faithful-muster-shell')}>
{tab==='chat'?<><div className='shell-titlebar external-chat-titlebar'><a href='#signal' className='shell-brand'><span className='external-app-symbol'>{channel==='Slack'?'#':'↗'}</span>{channel}</a><span><span className='slack-search-box'>⌕ Search Northstar Labs</span></span><select className='external-channel-select' aria-label='Story chat channel' value={channel} onChange={e=>setChannel(e.target.value)}><option>Slack</option><option>Telegram</option></select><button className='shell-expand' aria-label={expanded?'Collapse workspace':'Expand workspace'} onClick={()=>setExpanded(!expanded)}>{expanded?'Collapse':'Expand'}</button></div><div className='shell-body'><div className='shell-main'><ExternalChat channel={channel} step={step} final={final} onTag={()=>{setStep(1);setPlaying(motion)}} onRoute={()=>{setTab('roster');setRight('');setStep(Math.max(step,3))}} onPR={()=>{setRight('Pull request');setTab('code')}}/></div></div></>:<MusterWorkbench key={chapter+'-'+replayCount} {...{tab,setTab,step,setStep,playing,chapter,channel,selected,setSelected,stateFor,right,setRight,prTab,setPrTab,fixed,setFixed,approved,setApproved,requested,setRequested,note,setNote,recall,setRecall,receipt,setReceipt,browserValid,setBrowserValid,setPlaying}} onChat={backToChat}/>}
<div className='shell-playback'><button onClick={()=>setPlaying(!playing)} aria-label={playing?'Pause story animation':'Play story animation'}>{playing?<Pause/>:<Play weight='fill'/>}<span>{playing?'Pause':'Play'}</span></button><button onClick={replay}><ArrowCounterClockwise/>Replay chapter</button>{tab!=='chat'&&<button className='shell-expand' aria-label={expanded?'Collapse workspace':'Expand workspace'} onClick={()=>setExpanded(!expanded)}>{expanded?'Collapse':'Expand'}</button>}<div className='story-progress-track' aria-label={'Story progress '+Math.min(step+1,13)+' of 13'}>{Array.from({length:13},(_,i)=><button key={i} className={step>=i?'passed':''} aria-label={'Go to story beat '+(i+1)} onClick={()=>{setStep(i);setPlaying(false);setTab(i<3?'chat':i<5?'roster':i<7?'agent':i<9?'code':i<11?'computer':'chat');setRight(i>=9&&i<11?'Computer':i>=7&&i<9?'Pull request':'')}}/>)}</div><span>{String(Math.min(step+1,13)).padStart(2,'0')} / 13</span></div></div>}
